/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddAdminManager: typeof import('./components/AddAdminManager.vue')['default']
    AddApptUI: typeof import('./components/apptCmpt/AddApptUI.vue')['default']
    AddCourseDetailUI: typeof import('./components/courseCmpt/AddCourseDetailUI.vue')['default']
    AddCourseTypeUI: typeof import('./components/courseCmpt/AddCourseTypeUI.vue')['default']
    AddGoodsDetailUI: typeof import('./components/goodsCmpt/AddGoodsDetailUI.vue')['default']
    AddGoodsTypeUI: typeof import('./components/goodsCmpt/AddGoodsTypeUI.vue')['default']
    AddGroup: typeof import('./components/AddGroup.vue')['default']
    AddManager: typeof import('./components/AddManager.vue')['default']
    AddMember: typeof import('./components/AddMember.vue')['default']
    AddMemberBank: typeof import('./components/AddMemberBank.vue')['default']
    AddRoleManager: typeof import('./components/AddRoleManager.vue')['default']
    Alert: typeof import('./components/Alert.vue')['default']
    EditApptUI: typeof import('./components/apptCmpt/EditApptUI.vue')['default']
    EditCourseDetailUI: typeof import('./components/courseCmpt/EditCourseDetailUI.vue')['default']
    EditRoleName: typeof import('./components/editRoleName.vue')['default']
    GroupInfo: typeof import('./components/GroupInfo.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    MemberBankInfo: typeof import('./components/MemberBankInfo.vue')['default']
    MemberInfo: typeof import('./components/MemberInfo.vue')['default']
    RoleInfo: typeof import('./components/RoleInfo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
